journal/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('journal_entries.urls')),
    path('admin/', admin.site.urls),
    url(r'^select2/', include('django_select2.urls')),
]

journal_entries/urls.py
from django.urls import path

from . import views

app_name = 'journal_entries'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('create/', views.create_resource_ajax, name='ajax_create'),
    path('edit/<int:resource_id>/', views.update_resource_ajax, name='ajax_update'),
    path('delete/<int:resource_id>/', views.delete_resource_ajax, name='ajax_delete'),
    path('ajax_search/', views.ajax_search, name='ajax_search'),
]

journal_entries/models.py
from django.db import models


class Language(models.Model):
    tag = models.CharField(max_length=20)

    def __str__(self):
        return self.tag


class Framework(models.Model):
    tag = models.CharField(max_length=20)

    def __str__(self):
        return self.tag


class Resource(models.Model):
    title = models.CharField(max_length=50)
    description = models.CharField(max_length=1000)
    link = models.URLField()
    languages = models.ManyToManyField(Language)
    frameworks = models.ManyToManyField(Framework)
    pub_date = models.DateTimeField('date added')

    def __str__(self):
        return self.title

    @property
    def all_languages(self):
        return [x.tag for x in self.languages.all()]

    @property
    def all_frameworks(self):
        return [x.tag for x in self.frameworks.all()]

journal_entries/forms.py
from django import forms
from django_select2.forms import Select2MultipleWidget
from .models import Resource, Language, Framework


class ResourceForm(forms.ModelForm):
    class Meta:
        model = Resource
        fields = ['title', 'description', 'link', 'language', 'framework']

    title = forms.CharField(
        label='Title',
        max_length=50
    )

    description = forms.CharField(
        label='Description',
        max_length=200
    )

    link = forms.URLField()

    language = forms.ModelMultipleChoiceField(
        label='Add Language',
        queryset=Language.objects.all(),
        required=False,
        widget=Select2MultipleWidget(
            attrs={
                'style': 'float: center; width: 370px',
                'data-maximum-selection-length': 10
            },
        )
    )

    framework = forms.ModelMultipleChoiceField(
        label='Add Framework/Technology',
        queryset=Framework.objects.all(),
        required=False,
        widget=Select2MultipleWidget(
            attrs={
                'style': 'float: center; width: 370px',
                'data-maximum-selection-length': 10
            },
        )
    )

journal_entries/views.py
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect, JsonResponse
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils import timezone

import django_tables2 as tables

from .models import Resource, Language, Framework
from .tables import ResourceTable
from .forms import ResourceForm


class IndexView(tables.SingleTableView):
    template_name = 'journal_entries/index.html'
    model = Resource

    def get_queryset(self):
        return Resource.objects.order_by('-pub_date')

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        form = ResourceForm()
        table = ResourceTable(self.get_queryset())

        context['form'] = form
        context['table'] = table

        return context

    def post(self, request):
        form = ResourceForm(data=request.POST)
        if form.is_valid():

            new_resource = form.save(commit=False)
            new_resource.pub_date = timezone.now()
            new_resource.save()

        return HttpResponseRedirect(reverse('journal_entries:index'))


def create_resource_ajax(request):
    if request.method == 'POST':
        form = ResourceForm(request.POST)
    else:
        form = ResourceForm()

    return save_resource_form(request, form, 'journal_entries/partial_resource_create.html')


def update_resource_ajax(request, resource_id):
    resource = get_object_or_404(Resource, pk=resource_id)

    if request.method == 'POST':
        form = ResourceForm(request.POST, instance=resource)
    else:
        form = ResourceForm(instance=resource)

    return save_resource_form(request, form, 'journal_entries/partial_resource_update.html')


def delete_resource_ajax(request, resource_id):
    resource = get_object_or_404(Resource, pk=resource_id)
    data = dict()

    if request.method == 'POST':
        resource.delete()
        data['form_is_valid'] = True
        resource_list = Resource.objects.order_by('-pub_date')
        data['html_resource_list'] = ResourceTable(resource_list).as_html(request)
    else:
        context = {'resource': resource}
        data['html_form'] = render_to_string('journal_entries/partial_resource_delete.html',
                                             context,
                                             request=request,
                                             )

    return JsonResponse(data)


def save_resource_form(request, form, template_name):
    data = dict()

    if request.method == 'POST':
        if form.is_valid():

            new_resource = form.save(commit=False)

            if new_resource.pub_date is None:
                new_resource.pub_date = timezone.now()
            new_resource.save()

            languages = list(form.cleaned_data['language'])
            frameworks = list(form.cleaned_data['framework'])

            for language in languages:
                new_resource.languages.add(language)

            for framework in frameworks:
                new_resource.frameworks.add(framework)

            data['form_is_valid'] = True
            resource_list = Resource.objects.order_by('-pub_date')
            data['html_resource_list'] = ResourceTable(resource_list).as_html(request)
        else:
            data['form_is_valid'] = False

    context = {'form': form}
    data['html_form'] = render_to_string(template_name,
                                         context,
                                         request=request,
                                         )

    return JsonResponse(data)


def ajax_search(request):
    data = {}
    search_term = request.GET['search'].strip()
    search_class = request.GET['class'].strip()

    if search_class == 'language':
        language = Language.objects.get(tag=search_term)
        resource_list = language.resource_set.all().order_by('-pub_date')
    elif search_class == 'framework':
        framework = Framework.objects.get(tag=search_term)
        resource_list = framework.resource_set.all().order_by('-pub_date')
    else:
        resource_list = Resource.objects.all().order_by('-pub_date')

    data['html_resource_list'] = ResourceTable(resource_list).as_html(request)

    return JsonResponse(data)

journal_entries/templates/journal_entries/base.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'journal_entries/css/style.css' %}">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link href="http://cdnjs.cloudflare.com/ajax/libs/octicons/3.1.0/octicons.css" rel="stylesheet">
    {{ form.media.css }}
  </head>

  <body>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="//cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.23/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>
    <script>
      $(function () {

  var loadForm = function () {
    var btn = $(this);

    $.ajax({
      url: btn.attr("data-url"),
      type: 'get',
      dataType: 'json',
      beforeSend: function () {
        $("#modal-resource").modal("show");
      },
      success: function (data) {
        $("#modal-resource .modal-content").html(data.html_form);
      }
    });
  };


  var saveForm = function () {
    var form = $(this);

    $.ajax({
      url: form.attr("action"),
      data: form.serialize(),
      type: form.attr("method"),
      dataType: 'json',
      success: function (data) {
        if (data.form_is_valid) {
            $("#resource_list tbody").html(data.html_resource_list);
            $("#modal-resource").modal("hide");
            $('#resource_list').DataTable().clear()
            $('#resource_list').html(data['html_resource_list'])
            reloadDataform()
        }
        else {
          $("#modal-resource .modal-content").html(data.html_form);
        }
      }
    });
    return false;
  };


  $(".js-create-resource").click(loadForm);
  $("#modal-resource").on("submit", ".js-resource-create-form", saveForm);

  $("#resource_list").on("click", ".js-update-resource", loadForm);
  $("#modal-resource").on("submit", ".js-resource-update-form", saveForm);

  $("#resource_list").on("click", ".js-delete-resource", loadForm);
  $("#modal-resource").on("submit", ".js-resource-delete-form", saveForm);


  var filter = function(){
    var query = $(this).text();
    var classname = $(this).attr('class');
    event.preventDefault()
    $.ajax({
        url: "ajax_search/",
        dataType: 'json',
        data: {
            "class": classname,
            "search": query
        },

        success: function(data){
            $('#resource_list').DataTable().clear()
            $('#resource_list').html(data['html_resource_list'])
            reloadDataform()
        },

    });
  };


  var reloadDataform = function () {
    $('#resource_list').DataTable( {
        "sDom": 'lrtip',
        "destroy": true,
        "info" : false,
        "pageLength": 5,
        "lengthChange": false,
        "order": [[ 3, "desc" ]],
        "ordering": false,
        "columnDefs": [
         { width: 400, targets: [0,1,2,3] }
        ],
        "fixedColumns": true
    })


    $('.language').unbind().click(filter);
    $('.framework').unbind().click(filter);
    $('.search_filter').unbind().click(filter);


    $('.language').click(function () {
        var language = $(this).text()
        $('.search_filter').html(language);
        $('.search_filter').attr("id", language.trim().toLowerCase() )
    });

    $('.framework').click(function () {
        var framework = $(this).text()
        $('.search_filter').html(framework);
        $('.search_filter').attr("id", framework.trim().toLowerCase() )
    });

    $('.search_filter').click(function () {
        $('.search_filter').html('');
        $('.search_filter').attr("id", "hidden" )
    });

    $('#myInputTextField').keyup(function(){
        $('#resource_list').DataTable().search($(this).val()).draw() ;
    });
  }

  reloadDataform();
});
    </script>
    <script>
      /* global define, jQuery */
(function (factory) {
  if (typeof define === 'function' && define.amd) {
    define(['jquery'], factory)
  } else if (typeof module === 'object' && module.exports) {
    module.exports = factory(require('jquery'))
  } else {
    // Browser globals
    factory(jQuery)
  }
}(function ($) {
  'use strict'
  var init = function ($element, options) {
    $element.select2(options)
  }

  var initHeavy = function ($element, options) {
    var settings = $.extend({
      ajax: {
        data: function (params) {
          var result = {
            term: params.term,
            page: params.page,
            field_id: $element.data('field_id')
          }

          var dependentFields = $element.data('select2-dependent-fields')
          if (dependentFields) {
            dependentFields = dependentFields.trim().split(/\s+/)
            $.each(dependentFields, function (i, dependentField) {
              result[dependentField] = $('[name=' + dependentField + ']', $element.closest('form')).val()
            })
          }

          return result
        },
        processResults: function (data, page) {
          return {
            results: data.results,
            pagination: {
              more: data.more
            }
          }
        }
      }
    }, options)

    $element.select2(settings)
  }

  $.fn.djangoSelect2 = function (options) {
    var settings = $.extend({}, options)
    $.each(this, function (i, element) {
      var $element = $(element)
      if ($element.hasClass('django-select2-heavy')) {
        initHeavy($element, settings)
      } else {
        init($element, settings)
      }
      $element.on('select2:select', function (e) {
        var name = $(e.currentTarget).attr('name')
        $('[data-select2-dependent-fields=' + name + ']').each(function () {
          $(this).val('').trigger('change')
        })
      })
    })
    return this
  }

  $(function () {
    $('.django-select2').djangoSelect2()
  })

  return $.fn.djangoSelect2
}))

    </script>
  <!--    include 'includes/header.html' -->

    <div class="container">
      {% block content %}
      {% endblock %}
    </div>

    {% block javascript %}
    {% endblock %}
    {{ form.media.js }}
  </body>

</html>

journal_entries/templates/journal_entries/delete_button.html
<form method="post" action="{% url 'journal_entries:ajax_delete' record.id %}">
    <button type="button" class="close js-delete-resource"
            data-url="{% url 'journal_entries:ajax_delete' record.id %}"
            aria-label="Close">
        <span class="octicon octicon-trashcan"></span>
    </button>
</form>

journal_entries/templates/journal_entries/edit_button.html
<button type="button" class="btn btn-warning btn-sm js-update-resource"
                data-url="{% url 'journal_entries:ajax_update' record.id %}">
    <span class="octicon octicon-pencil"></span>
</button>

journal_entries/templates/journal_entries/index.html
{% extends 'journal_entries/base.html' %}
{% load static %}
{% load django_tables2 %}
{% block javascript %}
    <script src="{% static 'journal_entries/js/table_ajax.js' %}"></script>
{% endblock %}

{% block content %}
<h1> Journal Entries </h1> <br>

<p>
    <button type="button"
            class="btn btn-primary js-create-resource"
            data-url="{% url 'journal_entries:ajax_create' %}">
      <span class="octicon octicon-pin"></span>
        Add resource
    </button>
    <input id="myInputTextField" style="height: 40px; border-radius: 25px;" placeholder="search resources...">
    <a id="hidden" class="search_filter" href="{% url 'journal_entries:ajax_search' %}" style="text-decoration: none;"></a>
</p>

<br>

{% include 'journal_entries/partial_resource_list.html' %}

<div class="modal fade" id="modal-resource">
    <div class="modal-dialog">
      <div class="modal-content">
    </div>
</div>

{% endblock %}

journal_entries/templates/journal_entries/partial_resource_create.html
{% block headers %}
{{ form.media.css }}
{% endblock %}

{{form.media.js}}

<form method="post" action="{% url 'journal_entries:ajax_create' %}" class="js-resource-create-form">
  {% csrf_token %}
  <div class="modal-header">
    <h4 class="modal-title">Create a new resource</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    {% include 'journal_entries/partial_resource_form.html' %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Create resource</button>
  </div>
</form>

journal_entries/templates/journal_entries/partial_resource_form.html
{% load widget_tweaks %}
{% load static %}


{% for field in form %}
  <div class="form-group{% if field.errors %} has-error{% endif %}">
    {{ field.label_tag }}
    {% render_field field class="form-control" %}
    {% for error in field.errors %}
      <p class="help-block">{{ error }}</p>
    {% endfor %}
  </div>
{% endfor %}

journal_entries/templates/journal_entries/partial_resource_list.html
{% load django_tables2 %}
{% render_table table %}

journal_entries/templates/journal_entries/partial_resource_update.html
{% block headers %}
{{ form.media.css }}
{% endblock %}

{{form.media.js}}

<form method="post" action="{% url 'journal_entries:ajax_update' form.instance.pk %}" class="js-resource-update-form">
  {% csrf_token %}
  <div class="modal-header">
    <h4 class="modal-title">Update resource</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    {% include 'journal_entries/partial_resource_form.html' %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Update resource</button>
  </div>
</form>

journal_entries/templates/journal_entries/resource_form.html
<form method="POST">
    {% csrf_token %}
    <table>
        <tr>
            {% for field in form %}
                <td>  {{ field.errors }}
                    {{ field.label_tag }} {{ field }}
                    {% if field.help_text %}
                        <p class="help">{{ field.help_text|safe }}</p>
                    {% endif %}
                </td>
            {% endfor %}
            <td><input type="submit" value="Add resource"></td>
        </tr>
    </table>
</form>